---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: crudapp
        image: spacemax/crudapp:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: crudapp-service
spec:
  selector:
    app: tcrudapp
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer